[network]
address = "127.0.0.1"
max_connections = 100

[api]
address = "127.0.0.1:8080"

[blockchain]
rpc_url = "http://localhost:8545"
contract_address = "0x1234567890abcdef1234567890abcdef12345678"

[channel_listener]
polling_interval = 30

[global_root]
root_address = "0x1234567890abcdef1234567890abcdef12345678"
max_depth = 20
update_interval = 300
merkle_tree_type = "SparseMerkleTree"

[off_chain]
storage_path = "./storage"
max_cache_size = 10485760
sync_interval = 60
backup_enabled = true
backup_interval = 3600
compression_level = 5

[channel]
max_participants = 100
timeout_period = 600
min_deposit = 1000
max_deposit = 100000
challenge_period = 3600
dispute_resolution_mechanism = "on-chain"
state_update_interval = 300
max_state_size = 2048
